### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by davidjungman** [nettrine/orm#56]
In https://github.com/nettrine/orm/blob/master/.docs/README.md#setup

```
extensions:
    orm.annotations: Nettrine\ORM\DI\OrmAnnotationsExtension

orm.annotations:
    paths:
        - App/Model/Database/Entity
```

Instead of **App/Model/Database/Entity** use **%appDir%/Model/Entity** ?
