### ISSUE TITLE
Config for Codeception

### ISSUE THREAD

**Issue by mabezdek** [nettrine/orm#57]
Hello,
is it possible to use this integration with Codeception module Doctrine2? https://codeception.com/docs/modules/Doctrine2

How to eventually configure it (getEntityManager)?

Thanx.

**Comment by f3l1x** [comment]
Hi, I think it's possible to use it with codeception.

If you have a Container in some variable you can try:

```php
$em = $container->getByType(\Doctrine\ORM\EntityManagerInterface::class)
```

Or via neon file:

```yaml
xyz:
   setup:
      - setEm() // empty works too
      - setEm(@orm.entityManagerDecorator)
```

Let me know if it works.
